name: task_manager_coding_test
description: "Smart Task & Productivity App"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  # Routing
  go_router: ^14.8.1
  # Statemanagement
  flutter_bloc: ^9.1.0
  # Local Storage
  sqflite: ^2.4.1

  # Api Service
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0

  # Push Notifications
  flutter_local_notifications: ^19.0.0
  equatable: ^2.0.7
  path: ^1.9.0
  get_it: ^8.0.3
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Api Service
  retrofit_generator: ^9.1.9

  # Code Generator
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/db/task_manager_db.db
    - assets/gifts/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf_pro_display_regular.OTF
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
